### ISSUE TITLE
Use addition instead of multiplication?

### ISSUE THREAD

**Issue by bakketun** [monkeylord/bitcoin-ibe#2]
Is there a reason for using multiplication instead of addition as is done in BIP-32?

**Comment by monkeylord** [comment]
Still considering which one is better. Any advice?

**Comment by bakketun** [comment]
Using addition makes the computation of keys less expensive.

Calculating the private key is just an addition with modulus, instead of a multiplication.

Calculating the public key becomes BN * G + Pubkey. At first glance this is more complicated than just doing a multiplication, but G is a constant allowing for optimisations. Also note that this is the same operation as calculating the public key from a private key.

As far as I can understand the security is the same. Breaking it would still require to reverse a point multiplication.

**Comment by monkeylord** [comment]
My recent consideration is ECDSA signature.
If there are 2+ signature signed from different child key with same `r` and the deriving path(`Pubkey` and `ID`) is revealed, attacker may extract parent private key.
However, it's an old ECDSA security problem, deriving child key does just not mitigate it.
It seems neither addition, multiplication nor combination can mitigate it.

So, you are right. Addition is less expensive.
And I shall add hardened deriving.

**Comment by monkeylord** [comment]
Now use addition as default.
